<?php
/**
 * @file
 * batch_background_example.module
 */

/**
 * Implements hook_comment_save().
 */
function batch_background_example_comment_insert($comment) {
  // One of the best use cases for this is sending E-mails in the background.
  // The message and the message notify module, using the message example, will
  // display a good use case for how we can send a lot of emails.
  $node = node_load($comment->nid);
  if ($comment->uid == $node->uid) {
    // The comment author is also the node author, and we would ususally
    // return early here, but since this is an example, we send an email
    // anyway.
  }

  // Create a new message, assigned to the node author, and add a
  // reference to the comment, so we can later use tokens related to that
  // comment.
  $message = message_create('example_create_comment', array('uid' => $node->uid));
  $wrapper = entity_metadata_wrapper('message', $message);
  $wrapper->field_comment_ref->set($comment);
  $wrapper->field_node_ref->set($node);
  $wrapper->save();

  // After saving the message we need to store it in the batch info. The
  // callback function will use the message object and send it with
  // message_notify_send_message().
  batch_background_create()
    ->AddCallback('batch_background_example_send_message', array($wrapper->value()))
    ->save();
}

/**
 * Batch background callback; Send a message to the user.
 *
 * @see message_notify_example_comment_insert().
 */
function batch_background_example_send_message($message) {
  // When creating the comment we saved the message. Now, we can send it.
  message_notify_send_message($message);
}
